### ISSUE TITLE
Fresh Install On RPi3 Causes IndentationError

### ISSUE THREAD

**Issue by msw1970** [rkoshak/sensorReporter#57]
I'm attempting to use sensorReporter to deliver info into OpenHAB using the REST API... When I try to launch sensorReporter using sudo python sensorReporter.py sensorReporter.ini I get the following error..

Starting...
Loading sensorReporter.ini
Configuring logger: file = /var/log/sensorReporter.log size = 67108864 num = 10
Traceback (most recent call last):
  File "sensorReporter.py", line 207, in <module>
    main()
  File "sensorReporter.py", line 71, in main
    loadConfig(sys.argv[1])
  File "sensorReporter.py", line 194, in loadConfig
    createConnection(config, section)
  File "sensorReporter.py", line 173, in createConnection
    MyConn = getattr(importlib.import_module(module_name), class_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/sensorReporter/restConn.py", line 41
    def publish(self, message, destination):
    ^
IndentationError: unexpected indent

I've checked restConn.py for indentation errors but I can't find any..

**Comment by rkoshak** [comment]
This usually happens when 

1. running a Python program using Python3
2. a file has a mix of tabs and spaces

I usually am pretty careful about using only spaces but I didn't write the restConn.py script and don't really use it so it may have a mix of tabs and spaces. 

Try deleting the indentation on that line and replacing it with spaces to get it in the right position and that should fix it. If it does let me know. It will be quite some time before I'll get a chance to look into this.

**Comment by msw1970** [comment]
Hi... So, I've forced running the script with python2.7 and now getting a different error..

Starting...
Loading sensorReporter.ini
Configuring logger: file = /var/log/sensorReporter.log size = 67108864 num = 10
Traceback (most recent call last):
  File "sensorReporter.py", line 207, in <module>
    main()
  File "sensorReporter.py", line 71, in main
    loadConfig(sys.argv[1])
  File "sensorReporter.py", line 194, in loadConfig
    createConnection(config, section)
  File "sensorReporter.py", line 175, in createConnection
    connections[name] = MyConn(on_message, logger, params, sensors, actuators)
TypeError: __init__() takes exactly 4 arguments (6 given)

I'm struggling to work this one out

**Comment by rkoshak** [comment]
I bet the connector never got updated when two way communication was added
to the MQTT. You can add to new parameters to the init function of the rest
API connector. Since it doesn't support two way the last two parameters
would be ignored.

I'm on travel right now but if you can't handle this I'll take a look at it
when I get home.

**Comment by msw1970** [comment]
I'm happy to try/test, but I'm no Python programmer....

**Comment by rkoshak** [comment]
I'm not either. 😳 I'm just winging it.

**Comment by msw1970** [comment]
That sorted it.. Added sensors, actuators as parameters on the end of the init line in restConn.py

**Comment by rkoshak** [comment]
Awesome, if you can submit a PR that be awesome. For a change as little as this all you need to do is go [here](https://github.com/rkoshak/sensorReporter/blob/master/restConn.py), click the pencil and edit the file in browser, then save it and submit the PR. If you can't or don't want to let me know and I'll add it. But you may as well get the credit.

**Comment by rkoshak** [comment]
These have been fixed. I just tested out a fresh pull from github and there are no more indentation errors. I did not test the restConn errors but trust the PR submitted.
